config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login',
                                            sign_out: 'logout',
                                            sign_up: 'register'
                                           }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolio#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs|attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(sub_title: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: "Ruby on Rails")}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= "http://via.placeholder.com/600x400"
    self.thumb_image ||= "http://via.placeholder.com/350x150"
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout 'portfolio'
  access all: [:show, :index],
       user: {except: [:destroy, :new, :create, :update, :edit]},
       site_admin: :all


  def index
    @portfolio_items = Portfolio.all
  end

  def new
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build}

  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Porfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

  def edit
  end

  def update

    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show

  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private
  def portfolio_params

    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                     )
  end

  def set_portfolio_item
    @portfolio = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :portfolio_title %>
  </div>

  <div class="field">
    <%= form.label :sub_title %>
    <%= form.text_field :sub_title, id: :portfolio_sub_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :portfolio_body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technologies_form| %>
      <li>
        <%= technologies_form.label :name %>
        <%= technologies_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>

<p><%= portfolio.subtitle %></p>
<p><%= portfolio.body %></p>

<%= image_tag portfolio.thumb_image if portfolio.thumb_image %>
<%= link_to "Edit", edit_portfolio_path(portfolio) %>
<%= link_to "Delete", portfolio , method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', blogs_path %>

app/views/portfolios/index.html.erb
<h1> Portfolio Items </h1>

<%= link_to "Create new Item", new_portfolio_path if logged_in?(:admin_site) %>

<%= render partial: 'portfolio', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1> Create new Portfolio </h1>


<%= render 'form', portfolio: @portfolio_item %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio.main_image %>


<h1> <%= @portfolio.title %> </h1>

<em><%= @portfolio.subtitle %> </em>

<p><%= @portfolio.body %></p>

<h2> Technologies Used: </h2>

<% @portfolio.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>